version: '3.9'

services:
  postgres:
    image: postgres:16
    container_name: pg-wolt
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - postgres_data_jam:/var/lib/postgresql/data
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    env_file:
      - .env
    restart: unless-stopped
    networks:
      - db-api
  api:
    container_name: api-wolt
    depends_on:
      - postgres
    build: ./api
    ports:
      - "${API_PORT}:3000"
    restart: unless-stopped
    networks:
      - db-api
  application:
    container_name: application-wolt
    depends_on:
      - postgres
    build: ./webapp
    ports:
      - "${APP_PORT}:3000"
    restart: unless-stopped
volumes:
  postgres_data_jam:
networks:
  db-api: