CREATE TABLE IF NOT EXISTS promotions (
    id int GENERATED BY DEFAULT AS IDENTITY primary key,
    "year" int NOT NULL
);
CREATE TABLE IF NOT EXISTS users (
    mail varchar(128) PRIMARY KEY,
    promotion int NOT NULL,
    FOREIGN KEY (promotion) REFERENCES promotions(id)
);
CREATE TABLE IF NOT EXISTS log_time (
    id int GENERATED BY DEFAULT AS IDENTITY primary key,
    mail varchar(128) NOT NULL,
    "date" Date NOT NULL,
    duration int NOT NULL,
    FOREIGN KEY (mail) REFERENCES users(mail)
);